runtime: python311

service: default

env_variables:
  # These will be set in GCP Console or via gcloud
  # NOTION_API_KEY: your_key_here
  # MASTODON_INSTANCE_URL: your_url_here
  # MASTODON_ACCESS_TOKEN: your_token_here
  # OPEN_API_KEY: your_key_here
  # OPENROUTER_API_KEY: your_key_here
  # OPENROUTER_MODEL: nvidia/nemotron-3-nano-30b-a3b:free
  # REPLICATE_API_TOKEN: your_token_here
  # TELEGRAM_BOT_TOKEN: your_token_here
  # TELEGRAM_CHAT_ID: your_chat_id_here
  # NOTION_PAGE_URL: https://www.notion.so/Your-Page-URL
  # NOTION_POLL_INTERVAL: 60
  ENVIRONMENT: production

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

entrypoint: python -m uvicorn api_server:app --host 0.0.0.0 --port 8080
